// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kptsvdjfpeqiiweynunx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwdHN2ZGpmcGVxaWl3ZXludW54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxMTEzMDgsImV4cCI6MjA1NTY4NzMwOH0.IhDqM58YgrUYjMDm-gQjdHogph6mOwfw2F54Bhm2DPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);